### Dicionário → JSON → DataFrame (Duas Formas) → CSV
Ao trabalhar com JSON no Pandas, existem duas abordagens principais para carregar a informação em um DataFrame:

pd.DataFrame(json.loads(json_data)): Converte a string JSON para um objeto nativo do Python (dicionário/lista) e depois instancia o DataFrame. Ideal quando os dados já estão em memória.

pd.read_json(...): Lê diretamente uma string JSON ou um arquivo .json. Ideal para carregar arquivos do disco ou manipular strings JSON com formatos tabulares específicos usando o parâmetro orient.

In [1]:
import json
import pandas as pd

In [2]:
# Step 1: Dicionário original
dados_dict = {
    "nome": ["Ana", "Bruno", "Carla"],
    "idade": [25, 30, 22],
    "cidade": ["São Paulo", "Rio de Janeiro", "Curitiba"]
}

In [3]:
# Step 2: Converter Dicionário para string JSON
json_data = json.dumps(dados_dict, ensure_ascii=False, indent=4)
print("--- String JSON ---")
print(json_data)

--- String JSON ---
{
    "nome": [
        "Ana",
        "Bruno",
        "Carla"
    ],
    "idade": [
        25,
        30,
        22
    ],
    "cidade": [
        "São Paulo",
        "Rio de Janeiro",
        "Curitiba"
    ]
}

In [5]:
# -------------------------------------------------------------
# Abordagem A: json.loads + pd.DataFrame (via objeto Python)
# -------------------------------------------------------------
# json.loads() transforma a string JSON em dicionário Python
dados_python = json.loads(json_data)
df_opcao_a = pd.DataFrame(dados_python)

print("\n--- DataFrame (Opção A: json.loads) ---")
df_opcao_a

--- DataFrame (Opção A: json.loads) ---

    nome  idade          cidade
0    Ana     25       São Paulo
1  Bruno     30  Rio de Janeiro
2  Carla     22        Curitiba

In [6]:
# 2. Criar e gravar o arquivo .json usando json.dump
with open("json_data.json", "w", encoding="utf-8") as file:
    json.dump(dados_dict, file, ensure_ascii=False, indent=4)

print("Arquivo 'json_data.json' criado com sucesso!")

Arquivo 'json_data.json' criado com sucesso!

In [8]:
# -------------------------------------------------------------
# Abordagem B: pd.read_json (direto)
# -------------------------------------------------------------
df_opcao_b = pd.read_json('json_data.json')

print("\n--- DataFrame (Opção B: pd.read_json) ---")
df_opcao_b

--- DataFrame (Opção B: pd.read_json) ---

    nome  idade          cidade
0    Ana     25       São Paulo
1  Bruno     30  Rio de Janeiro
2  Carla     22        Curitiba

In [9]:
# Step 3: Salvar o DataFrame em CSV
df_opcao_a.to_csv("usuarios.csv", index=False, encoding="utf-8")
print("Arquivo 'usuarios.csv' gerado com sucesso!")

Arquivo 'usuarios.csv' gerado com sucesso!

### CSV → JSON

In [10]:
# Step 1: Criar o arquivo CSV de exemplo
dados = {
    "id": [1, 2, 3],
    "nome": ["Ana", "Bruno", "Carla"],
    "cargo": ["Analista", "Desenvolvedor", "Gerente"],
    "salario": [4500.00, 6200.00, 9500.00]
}

df_original = pd.DataFrame(dados)
df_original

   id   nome          cargo  salario
0   1    Ana       Analista   4500.0
1   2  Bruno  Desenvolvedor   6200.0
2   3  Carla        Gerente   9500.0

In [11]:
df_original.to_csv("dados_exemplo.csv", index=False, encoding="utf-8")
print("Arquivo criado com sucesso.")

Arquivo criado com sucesso.

In [12]:
# Step 2: Ler o arquivo CSV criado
df_csv = pd.read_csv("dados_exemplo.csv")

In [13]:
# Step 3: Converter o DataFrame para um arquivo .json
df_csv.to_json(
    "dados_saida.json",
    orient="records",   # Formata como lista de objetos (padrão de APIs)
    indent=4,           # Formata com indentação visual para leitura fácil
    force_ascii=False   # Preserva caracteres acentuados (como 'Gerente', 'São Paulo', etc.)
)

print("2. Arquivo 'dados_saida.json' gerado com sucesso!")

2. Arquivo 'dados_saida.json' gerado com sucesso!

orient='records' (A mais comum)
Organiza os dados como uma lista de dicionários/objetos. Cada dicionário representa uma linha da tabela. É o padrão utilizado pela maioria das APIs REST.

In [14]:
df_csv.to_json(
    "dados_saida2.json",
    orient="columns",
    indent=4,           # Formata com indentação visual para leitura fácil
    force_ascii=False   # Preserva caracteres acentuados (como 'Gerente', 'São Paulo', etc.)
)

orient='columns'

Organiza os dados agrupados por coluna. A chave principal é o nome da coluna, e o valor é um dicionário contendo o índice e o valor correspondente.

In [15]:
df_csv.to_json(
    "dados_saida3.json",
    orient="table",
    indent=4,           # Formata com indentação visual para leitura fácil
    force_ascii=False   # Preserva caracteres acentuados (como 'Gerente', 'São Paulo', etc.)
)

orient='table'

Exporta o JSON junto com um schema (metadados) detalhado que descreve os tipos de dados de cada coluna (inteiro, texto, data, etc.), além do bloco de dados (data). É ideal para reconstruir o DataFrame exatamente no mesmo estado.